### ISSUE TITLE
Can you also convert the text before and after the table?

### ISSUE THREAD

**Issue by Emasoft** [Xre0uS/Table2MD#1]
Can you also convert the text before and after the table? And the title of the HTML page or of the section (i.e. GitHub issue title)? 

So when saving the converted text, we can also save some context information about the content of the table.

Thanks!

**Comment by Xre0uS** [comment]
You mean to convert texts outside of the tables? But what would you want to convert them to since they're not in a table? You could just copy the titles or other information directly.
